apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-learning
  description: A simple Node.js service example
  annotations:
    github.com/project-slug: 'anuragpachauri/backstage-learning'
spec:
  type: service
  lifecycle: experimental
  owner: backstage
